# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

besselK_boost <- function(x, v) {
    .Call(`_bandle_besselK_boost`, x, v)
}

besselK <- function(x, v) {
    .Call(`_bandle_besselK`, x, v)
}

matern <- function(nu, a, rho, tau, D) {
    .Call(`_bandle_matern`, nu, a, rho, tau, D)
}

trenchDetcpp <- function(c) {
    .Call(`_bandle_trenchDetcpp`, c)
}

trenchInvcpp <- function(v) {
    .Call(`_bandle_trenchInvcpp`, v)
}

loglikeGPcpp <- function(Y, Z, A, logcovDet, sigmak, nk, D, Y2) {
    .Call(`_bandle_loglikeGPcpp`, Y, Z, A, logcovDet, sigmak, nk, D, Y2)
}

likelihoodGPcpp <- function(Xk, tau, h, nk, D, materncov = 0L, nu = 2) {
    .Call(`_bandle_likelihoodGPcpp`, Xk, tau, h, nk, D, materncov, nu)
}

gradientrhomatern <- function(Y, drvrhomatern, nk, D, Z, A, sigmak) {
    .Call(`_bandle_gradientrhomatern`, Y, drvrhomatern, nk, D, Z, A, sigmak)
}

gradientamatern <- function(Y, amatern, nk, D, Z, A, sigmak) {
    .Call(`_bandle_gradientamatern`, Y, amatern, nk, D, Z, A, sigmak)
}

gradientGPcppmatern <- function(Xk, tau, h, nk, D, nu) {
    .Call(`_bandle_gradientGPcppmatern`, Xk, tau, h, nk, D, nu)
}

LeapfrogGPcppPC <- function(Xk, lambda, tau, p, x, m, nk, D, L, delta, nu) {
    .Call(`_bandle_LeapfrogGPcppPC`, Xk, lambda, tau, p, x, m, nk, D, L, delta, nu)
}

sampleGPmeanmaterncpp <- function(Xk, tau, h, nk, D, nu) {
    .Call(`_bandle_sampleGPmeanmaterncpp`, Xk, tau, h, nk, D, nu)
}

makeComponent <- function(X, BX, Y, BY, j) {
    .Call(`_bandle_makeComponent`, X, BX, Y, BY, j)
}

normalisedDatamatern <- function(Xknown, BX, Xunknown, BXun, hypers, nk, tau, D, j, nu) {
    .Call(`_bandle_normalisedDatamatern`, Xknown, BX, Xunknown, BXun, hypers, nk, tau, D, j, nu)
}

centeredDatamatern <- function(Xknown, BX, Xunknown, BXun, hypers, nk, tau, D, K, nu) {
    .Call(`_bandle_centeredDatamatern`, Xknown, BX, Xunknown, BXun, hypers, nk, tau, D, K, nu)
}

componentloglike <- function(centereddata, sigmak) {
    .Call(`_bandle_componentloglike`, centereddata, sigmak)
}

comploglike <- function(centereddata, sigmak) {
    .Call(`_bandle_comploglike`, centereddata, sigmak)
}

comploglikelist <- function(centereddata, sigmak) {
    .Call(`_bandle_comploglikelist`, centereddata, sigmak)
}

sampleDirichlet <- function(numSamples, alpha) {
    .Call(`_bandle_sampleDirichlet`, numSamples, alpha)
}

sampleOutliercpp <- function(allocoutlierprob) {
    .Call(`_bandle_sampleOutliercpp`, allocoutlierprob)
}

sampleAlloccpp <- function(allocprob) {
    .Call(`_bandle_sampleAlloccpp`, allocprob)
}

#'  Copyright (C) 2014 Matteo Fasiolo  matteo.fasiolo@gmail.com
#'This program is free software; you can redistribute it and/or
#' modify it under the terms of the GNU General Public License
#' as published by the Free Software Foundation; either version 2
#' of the License, or (at your option) any later version.
#' This program is distributed in the hope that it will be useful,
#' but WITHOUT ANY WARRANTY; without even the implied warranty of
#' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#' GNU General Public License for more details.
#' (www.gnu.org/copyleft/gpl.html)
#' You should have received a copy of the GNU General Public License
#' along with this program; if not, write to the Free Software
#' Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
#' USA. */
NULL

mahaInt <- function(X, mu, sigma, isChol = FALSE) {
    .Call(`_bandle_mahaInt`, X, mu, sigma, isChol)
}

dmvtInt <- function(X, mu, cholDec, log, df) {
    .Call(`_bandle_dmvtInt`, X, mu, cholDec, log, df)
}

dmvtCpp <- function(X_, mu_, sigma_, df_, log_, isChol_) {
    .Call(`_bandle_dmvtCpp`, X_, mu_, sigma_, df_, log_, isChol_)
}

#' @title Computes gradients of hyperaparamters with respect to GP
#' 
#' @param Y The data
#' @param drv matrix derivative
#' @param nk number of observations
#' @param D number of samples
#' @param Z internal matrix required for computations
#' @param A internal matrix required for computations
#' @param sigmak standard deviation parameter
NULL

#' @title Computes gradients of  GP
#' @param Xk The data
#' @param tau indexing term
#' @param h vector of hyperparamters
#' @param nk number of observations
#' @param D number of samples
NULL

gradientGPcpp <- function(Xk, tau, h, nk, D) {
    .Call(`_bandle_gradientGPcpp`, Xk, tau, h, nk, D)
}

LeapfrogGPcpp <- function(Xk, tau, p, x, m, nk, D, L, delta) {
    .Call(`_bandle_LeapfrogGPcpp`, Xk, tau, p, x, m, nk, D, L, delta)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_bandle_rcpp_pgdraw`, b, c)
}

